### ISSUE TITLE
Problem With Assembling

### ISSUE THREAD

**Issue by ZoiksGoiks** [TesterTesterov/mesScriptAsseAndDissasembler#2]
Hello!

I've tried using your tool to edit .mes files from one of Silky's games called:

"Gakuen Saimin Reido -Sakki made, Daikirai Datta Hazu na no ni-"
https://vndb.org/v1601

Your tool dissembles the .mes file and creates the .txt file that I can edit. However, when I try to assemble the file back into a .mes archive, it always fails. Do you think you could take a look when you have the time?

Here's the link to one of that game's .mes files for you to take a look at:

https://anonfiles.com/xem9tfHfu5/MESExample_7z

Whatever you decide, thanks anyway!

ZoiksGoiks

**Comment by TesterTesterov** [comment]
Okay, I have fixed some things and assembling seems to work now.
Try yourself the [new release](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler/releases/tag/1.1).

**Comment by ZoiksGoiks** [comment]
> 
> 
> Okay, I have fixed some things and assembling seems to work now.
> Try yourself the [new release](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler/releases/tag/1.1).

Hello,

The assembling works now! Thanks a lot for responding and resolving my problem so quickly.

I have another problem, however. I tried putting the .mes files into the same folder where the game's '.exe' file is. However, the game always crashes, so it probably means that I have to repack the .mes files back into an .arc archive.

Do you have any idea how I can repack the extracted .mes files back into an .arc archive?

Thanks!

**Comment by TesterTesterov** [comment]
See [this topic](https://github.com/TesterTesterov/mesScriptAsseAndDisassembler/issues/1) (latest posts).

If the games crashes, it's either not-in-the-archive bug (yet commonly it works fine), or some offset- or command related problem.
So if it won't work in the archive, I'd probably need to seriously modify the tool to avoid this problem in the future. And I'd need the game files too.

**Comment by ZoiksGoiks** [comment]
I don't think your tool is causing any problems.

I extracted the 'Mes.arc' with GARbro, and then I tried placing the unedited, original '.mes' files inside same folder where the game's '.exe' file is, and it still crashes.

Do you have some sort of e-mail where I can contact you? I have the game, and I could send the link to you. 
I think that would be better than posting the link here.

Let me know.

Thank you!

**Comment by TesterTesterov** [comment]
It's testertesterovtesterovich@yandex.ru
Yet **you don't need to send me the game just yet**, since I won't have time to extensive tests anyway, if it is not really my tool fault. And it seems that it not.

If it's really so and it crashes even with pure .mes, then in this case it may be necessary to:
1. Extract all files from the archive and try without deleting archive.
2. Delete the archive afterwards.
3. Create the directory at the place of original arc archive and pull all extracted files where.

**Comment by ZoiksGoiks** [comment]
Hey, I figured it out. The game now loads properly with all the "pure/unedited" .mes files inside the same folder as the '.exe' file.
I just needed to edit one line inside the game's .INI file.

**However**, if I edit any of the .mes files with your tool and then place them inside the Game's folder, then game starts crashing. It gives me an error message in Japanese, which means something like:

"Stack doesn't exist (0)"

So it definitely has something to do with your tool. However, I understand that you're busy, so please don't worry about it.

Thank you for all your help :)

**Comment by TesterTesterov** [comment]
Okay. If it's problem with my tool, send me the game on the e-mail.
I don't know when I'll have time to fix it, but it does need to be fixed either way.

**Comment by ZoiksGoiks** [comment]
Okay, thank you! I'll do it later today.

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/133399571-02c0cd8f-733d-4a90-ab00-58a9a5691f52.png)
 yo I found a tool it can repack and compress Script.arc

**Comment by Cosetto** [comment]
https://github.com/crskycode/GalgameCoding/tree/main/GSIWin/Akeiro @TesterTesterov @ZoiksGoiks you can find the tool here

**Comment by Cosetto** [comment]
btw tester can you send me the link to the thread about how you change font of Silky's engine. I once saw it but I can't find it now

**Comment by TesterTesterov** [comment]
Oh, good to know about this tool.

Also, method to change the Silky engine font you may find [somewhere in my article, dedicated to Silky engine](https://anivisual.net/blog/2020-05-27-633). Some cases may be in comments.

**Comment by Cosetto** [comment]
I just realized that the tool I used to repack works only for silky's plus (silky engine), Silky's has an archive called mes.arc which contains .mes and that belongs to Ai5Win, Ai6Win, same engine with Elf. GARbro extracts Silky's plus scripts into .MES and AI5Win, AI6Win into .mes, maybe that's why the script tool didn't work with the game above

**Comment by TesterTesterov** [comment]
> tool didn't work with the game above

Actually, when I had time, I did check the game itself, not just only script. And I realized, that this .mes script, while it is not very far away from Silky Engine's, is not Silky Engine's. But this tool is ought to be used only with Silky Engine's scripts. So that's why it won't work with these MES. Ai6Win is not Silky Engine.

That's why I does not see the need to upgrade this tool to support this type of script anymore. I'd need to create completely different tool for Ai6Win and Ai5Win scripts, but I have other engines in plans before it.

**Comment by Cosetto** [comment]
https://github.com/mnakamura1337/engine_ai5v/blob/master/elf_mes.ksy this I guess and luckily ae-vn tool can repack ai6win 
![image](https://user-images.githubusercontent.com/81801486/137670871-08a04b1d-ded2-491c-9050-1ddfb6bca789.png)
And this one https://github.com/ssynn/game_translation seems interesting too

**Comment by Cosetto** [comment]
So I found this on tlwiki site the mestool and arctool they used for https://vndb.org/v1377 (Ai5win). It is written in python3. I think this might help https://web.archive.org/web/20140208002304/http://tlwiki.org/index.php?title=Kono_Yo_no_Hate_de_Koi_wo_Utau_Shoujo_YU-NO
Apparently I can't access to the latest version but previous version can be downloaded

**Comment by TesterTesterov** [comment]
@Cosetto, @ZoiksGoiks, I finally had time to hack the AI6WIN script format from the issue. It was, actually, even easier, then Silky Engine's. You can use [AI6WINScriptTool](https://github.com/TesterTesterov/AI6WINScriptTool) now.

With this the issue is officially closed. Hope it's not too late now.

===
Proof that it works...
![image](https://user-images.githubusercontent.com/66121918/147406889-3559c2cf-604f-4b66-ad6b-151c8e6fed02.png)

**Comment by ZoiksGoiks** [comment]
Hey, sorry to reopen this. This tool is working great. However, the Arc Tool can't seem to pack the images from the 'Layer.arc'.

Like, I can extract the image files from Layer.arc and get them all in the '.akb' format with the Arc Tool. 

https://github.com/TesterTesterov/AI6WINArcTool

However, the Arc Tool can't seem to pack the .akb images back into the Layer.arc archive.

Can you take a look when you find the time, please?

**Comment by Cosetto** [comment]
> Hey, sorry to reopen this. This tool is working great. However, the Arc Tool can't seem to pack the images from the 'Layer.arc'.
> 
> Like, I can extract the image files from Layer.arc and get them all in the '.akb' format with the Arc Tool.
> 
> https://github.com/TesterTesterov/AI6WINArcTool
> 
> However, the Arc Tool can't seem to pack the .akb images back into the Layer.arc archive.
> 
> Can you take a look when you find the time, please?

try using [arc_conv](https://github.com/amayra/arc_conv), usage: arc_conv --pack ai6 [folder] [output.arc]

**Comment by TesterTesterov** [comment]
> However, the Arc Tool can't seem to pack the .akb images back into the Layer.arc archive.

@ZoiksGoiks, strange. It should work, but quite slow due to implementation. What problem with packing do thou hath exactly?

**Comment by ZoiksGoiks** [comment]
Hey, you're absolutely right. It works, it's just SUPER slow haha


I don't have any more problems. I'm very grateful to you for all your work
and help. THANKS!

**Comment by Cosetto** [comment]
If  you need it to go faster then try arc_conv like I said above or ae-vn tool

**Comment by ZoiksGoiks** [comment]
Will do. Thank you!

**Comment by theinquisitor39** [comment]
> Hey, I figured it out. The game now loads properly with all the "pure/unedited" .mes files inside the same folder as the '.exe' file. I just needed to edit one line inside the game's .INI file.
> 
> **However**, if I edit any of the .mes files with your tool and then place them inside the Game's folder, then game starts crashing. It gives me an error message in Japanese, which means something like:
> 
> "Stack doesn't exist (0)"
> 
> So it definitely has something to do with your tool. However, I understand that you're busy, so please don't worry about it.
> 
> Thank you for all your help :)

@ZoiksGoiks what setting changes did you need to make?
